"""List of all current Dead by Daylight killers."""

killerList = [
    "artist",
    "blight",
    "cannibal",
    "cenobite",
    "clown",
    "deathslinger",
    "demogorgon",
    "doctor",
    "dredge",
    "executioner",
    "ghost face",
    "hag",
    "hillbilly",
    "huntress",
    "knight",
    "legion",
    "mastermind",
    "nemesis",
    "nightmare",
    "nurse",
    "oni",
    "onryo",
    "pig",
    "plague",
    "shape",
    "skull merchant",
    "spirit",
    "trapper",
    "trickster",
    "twins",
    "wraith"
]
